/* Données des stages — Campagne Shadow Moses (OCR du Comic, à vérifier au besoin). */
window.MGS_STAGES = [
  { id:1, name:"Cargo Dock (Tuto 1)", type:"sneak", time:"30 min", players:"1 (Snake)",
    tiles:["Board Tile","Elevator Shaft","Elevator"],
    guardDeck:"7 Rouges + 10 (sur 20) Bleues", reaction:"6 cartes Guard Reaction",
    guards:"x4", cameras:"—", events:["A : l'élévateur descend (pose la tuile Elevator + 1 garde)"],
    objective:["Interagir avec l'Élévateur PENDANT que ton jeton Alerté n'est PAS sur la carte"],
    special:["1 seule zone","Tutoriel : le Codec t'explique au fur et à mesure"] },

  { id:2, name:"Heliport (Tuto 2)", type:"sneak", time:"45 min", players:"1",
    tiles:["Heliport A","Heliport B","Heliport C","Heliport D"],
    guardDeck:"7 Rouges + 13 Bleues", guards:"x4", cameras:"x3", events:["x2"],
    objective:["Atteindre la sortie (voir comic)"],
    special:["Introduction des jetons Focus"] },

  { id:3, name:"Holding Cells", type:"sneak", time:"45 min", players:"1-2 (Snake / Meryl)",
    tiles:["Holding Cells","Armory","2 Elevator Shafts","Elevator","Barracks"],
    guardDeck:"7 Rouges + 13 Bleues", guards:"voir Barracks/zones", cameras:"—",
    objective:["Vaincre 12 gardes dans les Holding Cells","OU atteindre l'objectif puis la Sortie"],
    special:["Plusieurs zones (bordures orange)","Meryl jouable à partir d'ici","Setup : jeton Alerté sous chaque figurine ; Élévateur sur le shaft de la zone de départ"] },

  { id:4, name:"Ocelot (Boss)", type:"boss", time:"30 min", players:"1",
    tiles:["Ocelot Stage"],
    boss:{ name:"Revolver Ocelot",
      setup:["Pose le dashboard + la figurine Ocelot","Carte Référence Boss standard sur chaque dashboard joueur","Mets la carte RELOAD de côté, face cachée","Pioche 4 cartes Ocelot AU HASARD (renvoie les 2 inutilisées)","Place la carte RELOAD au FOND du deck Boss"],
      note:"Boss : tu encaisses/évites ses attaques et tu lui infliges des dégâts. Sa carte RELOAD au fond le force à recharger." },
    objective:["Vaincre Ocelot"], special:["Stage Boss : pas de gardes ni Guard deck"] },

  { id:5, name:"Tank (Boss)", type:"boss", time:"30 min", players:"1",
    tiles:["Snow Field A","Snow Field B"],
    boss:{ name:"M1 Tank",
      setup:["Mélange le deck Boss du Tank","Carte Special Action « Grenade » sur chaque dashboard (+ jetons charge)"],
      note:"Utilise les grenades pour endommager le tank." },
    objective:["Détruire le Tank"], cleared:"Débloque la carte Équipement #007" },

  { id:6, name:"Nuclear Warhead Storage", type:"sneak", time:"60 min", players:"1",
    tiles:["Nuke Building L1","Nuke Truck","Nuke Building B1","Nuke Building B2","3 Elevator Shafts","Elevator","Barracks"],
    guardDeck:"7 Rouges + 18 Bleues", guards:"voir zones", cameras:"—",
    objective:["1) Détruire le Switchboard en B2 (amène un perso sur sa case)","2) Atteindre la Sortie en B2"],
    special:["🚫 NO FIRE ZONE : aucune arme à distance / explosif sur L1 et Truck","Élévateur utilisable via Interagir"] },

  { id:7, name:"Cyborg Ninja (Boss)", type:"boss", time:"60 min", players:"1",
    tiles:["Laboratory"],
    boss:{ name:"Cyborg Ninja (Gray Fox)",
      setup:["Carte Référence Boss standard sur chaque dashboard","Mélange les 5 cartes Cyborg Ninja (deck Boss)","Prépare les 4 jetons Shadow"],
      note:"Snake ne peut PAS faire de Silent/Sneak Takedown contre lui (« Always on Guard »)." },
    objective:["Vaincre le Cyborg Ninja"], special:["Snake : pas de Sneak Attack sur ce boss"], cleared:"Débloque la carte #001" },

  { id:8, name:"Psycho Mantis (Boss)", type:"boss", time:"45 min", players:"2",
    tiles:["Commander's Room"],
    boss:{ name:"Psycho Mantis",
      setup:["Carte Référence Boss standard sur chaque dashboard","Mélange les 7 cartes Psycho Mantis (deck Boss)","Marqueur Menace sur la case la plus haute de la piste Threat"],
      note:"Mantis a une piste de Menace (Threat track)." },
    objective:["Vaincre Psycho Mantis"],
    special:["Mobilier (lignes jaunes pointillées) : infranchissable, mais ne bloque PAS la LOS — on peut tirer à travers"], cleared:"Débloque la carte #013" },

  { id:9, name:"Prison — Libérer Snake & Meryl", type:"sneak", time:"60 min", players:"1-2",
    tiles:["Interrogation Room","Prison Cell","Security Room","3 Elevator Shafts","Elevator"],
    guardDeck:"1j : 7R+16B  ·  2j : 7R+12B", guards:"voir zones", cameras:"—",
    objective:["Libérer Snake (déverrouiller la porte de sa cellule)","Libérer Meryl (déverrouiller la porte de sa cellule)","(dans n'importe quel ordre)"],
    special:["6 jetons Objectif mélangés et placés","Otacon : deck System standard","Objectif : en gagnant la LOS sur un jeton, on le révèle ; le bon = figurine Meryl, sinon défausse","Élévateur déplaçable via Interagir"] },

  { id:10, name:"Hind D — Hélico (Boss)", type:"boss", time:"35 min", players:"1",
    tiles:["Comms Tower Roof","Helicopter Gunship"],
    boss:{ name:"Helicopter Gunship (Hind D)",
      setup:["Carte Special Action « Lance-missiles sol-air (SAM) » sur chaque dashboard","Mélange les 6 cartes Hind (deck Boss)","Marqueur Menace sur la case la plus à gauche","Otacon : carte Référence Terminal + deck System « Helicopter Gunship » + 2 jetons (Turret) "],
      note:"Vise l'hélico avec le lance-missiles SAM." },
    objective:["Vaincre le Hind D"] },

  { id:11, name:"Sniper Wolf (Boss)", type:"boss", time:"40-50 min", players:"1-3 (+ Otacon en infiltration)",
    tiles:["Sniper Wolf","Snowfield B"],
    boss:{ name:"Sniper Wolf",
      setup:["Carte Special Action « Sniper Rifle » sur Snake / Meryl / Gray Fox","Otacon joue en INFILTRATION en parallèle (deck Guard Order 7R+10B)","Deck System d'Otacon : 2x Remote Unlock, 1x Misdirection, 1x Distraction"],
      note:"⚠️ Sniper Wolf résout son tour AVANT l'activation des gardes. Otacon a ses propres objectifs : 1) déverrouiller la porte de Sécurité niv.5  2) finir un tour sur la tuile Sniper Wolf." },
    objective:["Vaincre Sniper Wolf"], special:["Les arbres sont des obstacles (mais les Crosshairs passent à travers)"] },

  { id:12, name:"Vulcan Raven (Boss)", type:"boss", time:"45 min", players:"3-4",
    tiles:["Warehouse A","Warehouse B"],
    boss:{ name:"Vulcan Raven",
      setup:["Carte Référence Boss standard sur chaque dashboard","Mélange les 5 cartes Vulcan Raven (deck Boss)","Marqueur Menace sur la case la plus à gauche","Otacon : carte Référence Terminal + deck System « Vulcan Raven » + 2 jetons Turret"],
      note:"" },
    objective:["Vaincre Vulcan Raven"], cleared:"Débloque la carte #021" },

  { id:13, name:"PAL Override", type:"sneak", time:"voir comic", players:"voir comic",
    tiles:["voir comic p.28-29"],
    objective:["Override des codes PAL (voir comic)"],
    special:["Stage à compléter (OCR partiel) — dis-moi de relire les pages 28-29 si besoin"] },

  { id:14, name:"Metal Gear REX (Boss final)", type:"boss", time:"voir comic", players:"voir comic",
    tiles:["voir comic p.30-32"],
    boss:{ name:"Metal Gear REX",
      setup:["Voir comic (setup détaillé p.30-32)"],
      note:"2 phases : 1) Détruire le RADÔME avec un missile à tête chercheuse → force l'ouverture du cockpit  2) Tirer un missile dans le cockpit pour détruire l'ordinateur de contrôle. Le blindage frontal est impénétrable : vise les capteurs/le radôme." },
    objective:["Détruire Metal Gear REX (radôme puis cockpit)"] },
];
